/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empmgmt.gui;

import empmgmt.dbutil.DbConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author welcome
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionsFrame
     */
    public OptionsFrame() {
        super("Emp Management System");
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioAdd = new javax.swing.JRadioButton();
        radioSearch = new javax.swing.JRadioButton();
        radioShow = new javax.swing.JRadioButton();
        radioExit = new javax.swing.JRadioButton();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("SELECT AN OPTONS");

        radioAdd.setBackground(new java.awt.Color(0, 102, 102));
        radioAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radioAdd.setForeground(new java.awt.Color(255, 255, 255));
        radioAdd.setText("ADD EMPLOYEE");
        radioAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddActionPerformed(evt);
            }
        });

        radioSearch.setBackground(new java.awt.Color(0, 102, 102));
        radioSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radioSearch.setForeground(new java.awt.Color(255, 255, 255));
        radioSearch.setText("SEARCH EMPLOYEE");

        radioShow.setBackground(new java.awt.Color(0, 102, 102));
        radioShow.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radioShow.setForeground(new java.awt.Color(255, 255, 255));
        radioShow.setText("SHOW ALL EMPLOYEE");

        radioExit.setBackground(new java.awt.Color(0, 102, 102));
        radioExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        radioExit.setForeground(new java.awt.Color(255, 255, 255));
        radioExit.setText("EXIT");

        btn.setBackground(new java.awt.Color(0, 102, 102));
        btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn.setForeground(new java.awt.Color(0, 102, 102));
        btn.setText("CLICK");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioExit)
                    .addComponent(radioAdd)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioSearch)
                    .addComponent(radioShow))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(radioAdd)
                .addGap(65, 65, 65)
                .addComponent(radioSearch)
                .addGap(68, 68, 68)
                .addComponent(radioShow)
                .addGap(52, 52, 52)
                .addComponent(radioExit)
                .addGap(51, 51, 51)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAddActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        if(validateInput() == false) {
            JOptionPane.showMessageDialog(null,"Please Select One Option");
            return;
        }
        JFrame frame = null;
        if(radioAdd.isSelected()) {
            frame = new AddEmployeeFrame();
        }
        else if(radioSearch.isSelected()) {
             frame = new SearchEmployeeFrame();
        }
        else if(radioShow.isSelected()) {
             frame = new ShowAllEmployeeFrame();
        }
        else {
            JOptionPane.showMessageDialog(null,"Thank You for Using");
            DbConnection.CloseDbConnection();
        }
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioAdd;
    private javax.swing.JRadioButton radioExit;
    private javax.swing.JRadioButton radioSearch;
    private javax.swing.JRadioButton radioShow;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
        if(radioAdd.isSelected() == false && radioSearch.isSelected() == false && radioShow.isSelected() == false && radioExit.isSelected() == false) 
            return false;
        return true;
    }
}
